# Generated by Django 4.0.10 on 2026-02-21 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='practice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.practice'),
            preserve_default=False,
        ),
    ]
