# Generated by Django 4.0.10 on 2026-02-16 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0002_alter_patient_age_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[{'c': 'Completed', 'p': 'Pending'}], max_length=50)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.claim')),
            ],
        ),
    ]
