# Generated by Django 4.0.10 on 2026-02-21 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_procedure_practice'),
        ('claim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='organization.practice'),
        ),
    ]
