# Generated by Django 4.0.10 on 2026-02-19 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('patient', '0002_alter_patient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='organization.practice'),
        ),
    ]
