# Generated by Django 4.0.10 on 2026-02-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patient_address_patient_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='moinakf@gmail.com', max_length=50),
        ),
    ]
