# Generated by Django 4.0.10 on 2026-02-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'SuperAdmin'), ('orgadmin', 'OrgAdmin'), ('pracadmin', 'PracAdmin')], max_length=20),
        ),
    ]
